GET http://localhost:1234/movies

###RECUPERAR POR ID
GET http://localhost:1234/movies/574c3822-0780-47ba-9cb9-2c4926ea3bfc

####RECUPERAR TODAS PELICULAS POR GENERO
GET http://localhost:1234/movies?genre=Action

### CREAR UNA PELICULA
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title":"The godfather",
    "year":1975,
    "director":"Francis Ford Coppola",
    "duration":175,
    "poster":"https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre":[
        "Crime",
        "Drama"
    ]
}

### ACTUALIZAR UNA PELICULA 
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year":1972
}